### ISSUE TITLE
What is the purpose to redefine EV_COMMON?

### ISSUE THREAD

**Issue by yichya** [wangyu-/udp2raw-tunnel#240]
I'm trying to compile udp2raw-tunnel with dynamically linked libev to reduce firmware size. However in `my_ev_common.h`, `EV_COMMON` is redefined as `void* data, unsigned long long u64`, thus pre-compiled libev cannot be used here (immediate segmentation fault on start). Deleting the statement to redefine `EV_COMMON` solve my problem and it seems not changing anything, so I just wonder what is the purpose to redefine this macro and will it lead to some negative effect if deleted?

-------

Chinese:

我在尝试用动态链接的方式编译 udp2raw-tunnel 以便节省空间，但是在 `my_ev_common.h` 中 `EV_COMMON` 被重新定义为了 `void* data, unsigned long long u64`，这样如果不重新编译 libev 的话就不能使用（启动的时候马上 Segmentation Fault）。我把这一行去掉就可以使用未修改的 libev 了，而且删掉这个似乎对程序并没有产生什么影响，因此想请教一下：这里重新定义的意义是什么？删除这个定义会有什么影响嘛？

**Comment by wangyu-** [comment]
Previous this program was backended by epoll, later it was changed to libev. Redefining `EV_COMMON`  make the transfer process easier.

Looks like, yes, for udp2raw it's no longer necessary to redine EV_COMMON.  The redefining is keep there to make it consistent with UDPspeeder and tinyportMapper, so that they can use same pre-compiled windows version of libev.

>Deleting the statement to redefine EV_COMMON solve my problem and it seems not changing anything, so I just wonder what is the purpose to redefine this macro and will it lead to some negative effect if deleted?

There is no side effect as long as it compiles successfully.
