### ISSUE TITLE
reconncet, can not connect,school firewall ?

### ISSUE THREAD

**Issue by stuxnet** [wangyu-/udp2raw-tunnel#363]
English Only (except for bug reporting).
![image](https://user-images.githubusercontent.com/2310075/101316512-91119d80-3897-11eb-9201-03144defc21d.png)

**Comment by wangyu-** [comment]
Below are some common reasons:
1. you didn't add the local firewall rule (produced by `-g` option) correctly.  In this case you should add and re-try.   
2. your school might be using some proxy-based method for traffic local balancing.  this kind of environment doesn't alow raw socket to pass correctly. So unfortunately if this is the case, the problem is not solvable

**Comment by stuxnet** [comment]
> 
> 
> Below are some common reasons:
> 
>     1. you didn't add the local firewall rule (produced by `-g` option) correctly.  In this case you should add and re-try.
> 
>     2. your school might be using some proxy-based method for traffic local balancing.  this kind of environment doesn't alow raw socket to pass correctly. So unfortunately if this is the case, the problem is not solvable
