### ISSUE TITLE
how about add Dockerfile

### ISSUE THREAD

**Issue by zhangguanzhang** [wangyu-/udp2raw-tunnel#370]
I test it works ok on my ecs and openwrt.

server:
```
docker run \
    -d --name udp2raw  \
    --net host \
    --cap-add NET_RAW \
    --cap-add NET_ADMIN  \
    zhangguanzhang/udp2raw \
    -s -l 0.0.0.0:86 \
    -r 127.0.0.1:16000 \
    -k passwd123 \
    --raw-mode faketcp  \
    --cipher-mode xor  -a
```
client:
```
docker run --net host \
    -d --name udp2raw  \
    --cap-add NET_RAW \
    --cap-add NET_ADMIN    \
    zhangguanzhang/udp2raw \
    -c -l 0.0.0.0:16000 \
    -r <public_ip>:86 \
    -k passwd123 \
    --raw-mode faketcp   \
    --cipher-mode xor  -a
```

**Comment by wangyu-** [comment]
Previously, I have made a dockerfile:
https://github.com/wangyu-/udp2raw-tunnel/pull/60

It works on linux, but it was hard to make it work on windows and macOS correctly, since docker doesn't seem to support raw socket very well.  I didn’t pay attention later, since it kind of loses the advantage of using docker if it only works under linux.

**Comment by zhangguanzhang** [comment]
I didn’t notice that there is already a Dockerfile, regardless of non-Linux platforms. Now many openwrts support docker, so Docker still exists.
